# Generated by Django 4.2.5 on 2023-10-03 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Carro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelo", models.CharField(max_length=100)),
                ("marca", models.CharField(max_length=50)),
                ("cor", models.CharField(max_length=50)),
                ("placa", models.CharField(max_length=20)),
                ("ano", models.IntegerField()),
            ],
            options={
                "verbose_name": "Carro",
                "verbose_name_plural": "Carros",
            },
        ),
        migrations.CreateModel(
            name="Condutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Condutor",
                "verbose_name_plural": "Condutores",
            },
        ),
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=15)),
                ("whatsapp", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                "verbose_name": "Contato",
                "verbose_name_plural": "Contatos",
            },
        ),
        migrations.CreateModel(
            name="EnderecoDestino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=10)),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("municipio_uf", models.CharField(max_length=100)),
                ("cep", models.CharField(max_length=10)),
                ("referencia", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Endereço de Destino",
                "verbose_name_plural": "Endereços de Destino",
            },
        ),
        migrations.CreateModel(
            name="EnderecoOcorrencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=10)),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("municipio_uf", models.CharField(max_length=100)),
                ("cep", models.CharField(max_length=10)),
                ("referencia", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Endereço da Ocorrência",
                "verbose_name_plural": "Endereços da Ocorrência",
            },
        ),
        migrations.CreateModel(
            name="Imagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="pictures/%Y/%m/")),
            ],
            options={
                "verbose_name": "Imagem",
                "verbose_name_plural": "Imagens",
            },
        ),
        migrations.CreateModel(
            name="Seguradora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_seguradora",
                    models.CharField(
                        choices=[
                            ("Seguradora A", "Seguradora A"),
                            ("Seguradora B", "Seguradora B"),
                            ("Seguradora C", "Seguradora C"),
                        ],
                        max_length=20,
                    ),
                ),
                ("solicitante", models.CharField(max_length=90)),
                ("produto", models.CharField(max_length=90)),
            ],
            options={
                "verbose_name": "Seguradora",
                "verbose_name_plural": "Seguradoras",
            },
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saida", models.DecimalField(decimal_places=2, max_digits=12)),
                ("km_excedente", models.DecimalField(decimal_places=2, max_digits=12)),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
            },
        ),
        migrations.CreateModel(
            name="Viagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sinistro", models.IntegerField(unique=True)),
                ("data", models.DateField()),
                ("hora", models.TimeField()),
                ("previsao", models.CharField(max_length=40)),
                ("causa_assistencia", models.CharField(max_length=60)),
                ("descricao", models.TextField()),
                (
                    "carro",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="viagens.carro",
                    ),
                ),
                (
                    "condutor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="viagens.condutor",
                    ),
                ),
                (
                    "contato",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="viagens.contato",
                    ),
                ),
                (
                    "endereco_destino",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="viagens.enderecodestino",
                    ),
                ),
                (
                    "endereco_ocorrencia",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="viagens.enderecoocorrencia",
                    ),
                ),
                ("imagens", models.ManyToManyField(blank=True, to="viagens.imagem")),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seguradora",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="viagens.seguradora",
                    ),
                ),
                (
                    "servico",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="viagens.servico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Viagem",
                "verbose_name_plural": "Viagens",
            },
        ),
    ]
