# Generated by Django 4.2.5 on 2023-09-29 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("viagens", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ViagemModel",
            new_name="Viagem",
        ),
    ]
