# Generated by Django 4.2.5 on 2023-09-29 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("viagens", "0002_rename_viagemmodel_viagem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carro",
            options={"verbose_name": "Carro", "verbose_name_plural": "Carros"},
        ),
        migrations.AlterModelOptions(
            name="contato",
            options={"verbose_name": "Contato", "verbose_name_plural": "Contatos"},
        ),
        migrations.AlterModelOptions(
            name="enderecodestino",
            options={
                "verbose_name": "EnderecoDestino",
                "verbose_name_plural": "EnderecoDestinos",
            },
        ),
        migrations.AlterModelOptions(
            name="enderecoocorrencia",
            options={
                "verbose_name": "EnderecoOcorrencia",
                "verbose_name_plural": "EnderecoOcorrencias",
            },
        ),
        migrations.AlterModelOptions(
            name="seguradora",
            options={
                "verbose_name": "Seguradora",
                "verbose_name_plural": "Seguradoras",
            },
        ),
        migrations.AlterModelOptions(
            name="servico",
            options={"verbose_name": "Servico", "verbose_name_plural": "Servicos"},
        ),
        migrations.AlterModelOptions(
            name="viagem",
            options={"verbose_name": "Viagem", "verbose_name_plural": "Viagens"},
        ),
    ]
