# Generated by Django 4.2.5 on 2023-09-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viagens", "0003_alter_carro_options_alter_contato_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Imagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="imagens_produtos/")),
            ],
        ),
        migrations.AddField(
            model_name="viagem",
            name="imagens",
            field=models.ManyToManyField(blank=True, to="viagens.imagem"),
        ),
    ]
