# Generated by Django 4.2.5 on 2023-09-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viagens", "0004_imagem_viagem_imagens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagem",
            name="imagem",
            field=models.ImageField(upload_to="pictures/%Y/%m/"),
        ),
    ]
