# Generated by Django 4.2.5 on 2023-09-29 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("viagens", "0005_alter_imagem_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Condutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name="viagem",
            name="carro",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="viagens.carro",
            ),
        ),
        migrations.AlterField(
            model_name="viagem",
            name="contato",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="viagens.contato",
            ),
        ),
        migrations.AlterField(
            model_name="viagem",
            name="endereco_destino",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="viagens.enderecodestino",
            ),
        ),
        migrations.AlterField(
            model_name="viagem",
            name="endereco_ocorrencia",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="viagens.enderecoocorrencia",
            ),
        ),
        migrations.AlterField(
            model_name="viagem",
            name="seguradora",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="viagens.seguradora",
            ),
        ),
        migrations.AlterField(
            model_name="viagem",
            name="servico",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="viagens.servico",
            ),
        ),
        migrations.AddField(
            model_name="viagem",
            name="condutor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="viagens.condutor",
            ),
        ),
    ]
