# Generated by Django 4.2.5 on 2023-09-29 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("viagens", "0006_condutor_alter_viagem_carro_alter_viagem_contato_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="condutor",
            options={"verbose_name": "Condutor", "verbose_name_plural": "Condutores"},
        ),
        migrations.AlterModelOptions(
            name="enderecodestino",
            options={
                "verbose_name": "Endereço de Destino",
                "verbose_name_plural": "Endereços de Destino",
            },
        ),
        migrations.AlterModelOptions(
            name="enderecoocorrencia",
            options={
                "verbose_name": "Endereço da Ocorrência",
                "verbose_name_plural": "Endereços da Ocorrência",
            },
        ),
        migrations.AlterModelOptions(
            name="imagem",
            options={"verbose_name": "Imagem", "verbose_name_plural": "Imagens"},
        ),
        migrations.AddField(
            model_name="viagem",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
